"""Turning a checked pin map into something firmware can include.

The point of exporting rather than hand-copying: the header and the Python
constants come from the same registry that already refused the bad assignments,
so the two halves of a project cannot drift apart. If the display moves to a
different pin, the header changes on the next build and the static asserts stay
true - or the build stops.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from .registry import Assignment, PinRegistry

#: C++ identifiers cannot start with a digit and cannot contain '.', which is
#: exactly what bus roles like "display.sda" are made of.
_NOT_IDENTIFIER = re.compile(r"[^0-9A-Za-z]+")

#: Pairwise static asserts are O(n^2) lines. Past this many pins the header
#: stops being readable and the value of the check does not keep up with it.
MAX_STATIC_ASSERT_PINS = 24


def identifier(role: str, *, prefix: str = "PIN_") -> str:
    """``display.sda`` -> ``PIN_DISPLAY_SDA``."""
    cleaned = _NOT_IDENTIFIER.sub("_", role).strip("_").upper()
    if not cleaned:
        raise ValueError(f"role {role!r} has no characters usable in an identifier")
    if cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return f"{prefix}{cleaned}"


def _unique_identifiers(
    assignments: Iterable[Assignment], prefix: str
) -> list[tuple[str, Assignment]]:
    """Distinct roles can collide once punctuation is stripped; disambiguate."""
    used: dict[str, int] = {}
    out: list[tuple[str, Assignment]] = []
    for assignment in assignments:
        name = identifier(assignment.role, prefix=prefix)
        if name in used:
            used[name] += 1
            name = f"{name}_{used[name]}"
        else:
            used[name] = 1
        out.append((name, assignment))
    return out


def _comment(registry: PinRegistry, assignment: Assignment) -> str:
    spec = registry.profile.pin(assignment.pin)
    bits = []
    if assignment.capabilities:
        bits.append(", ".join(c.value for c in assignment.capabilities))
    if spec.aliases:
        bits.append(f"aka {', '.join(spec.aliases)}")
    if assignment.note:
        bits.append(assignment.note)
    return "; ".join(bits)


def to_cpp_header(
    registry: PinRegistry,
    *,
    namespace: str = "pins",
    prefix: str = "PIN_",
    guard: str = "",
    include_advisories: bool = True,
) -> str:
    """Emit a header of ``constexpr int`` pin numbers.

    ``constexpr int`` rather than macros so that the values keep a type, respect
    the namespace, and show up in a debugger.
    """
    entries = _unique_identifiers(registry.assignments, prefix)
    profile = registry.profile

    lines: list[str] = [
        "// Generated by pinguard. Edit the pin map, not this file.",
        f"// Board: {profile.display_name or profile.name}",
        f"// Profile fingerprint: {profile.fingerprint()}",
        "",
    ]
    if guard:
        lines += [f"#ifndef {guard}", f"#define {guard}", ""]
    else:
        lines += ["#pragma once", ""]

    if namespace:
        lines += [f"namespace {namespace} {{", ""]

    if not entries:
        lines.append("// No pins claimed.")
    for name, assignment in entries:
        comment = _comment(registry, assignment)
        if comment:
            lines.append(f"// {assignment.role}: {comment}")
        else:
            lines.append(f"// {assignment.role}")
        lines.append(f"inline constexpr int {name} = {assignment.pin};")
        lines.append("")

    if include_advisories and registry.advisories:
        lines.append("// Advisories carried over from the pin map:")
        lines += [f"//   {item}" for item in registry.advisories]
        lines.append("")

    if 1 < len(entries) <= MAX_STATIC_ASSERT_PINS:
        lines.append("// Two roles sharing a pin is a bus conflict, not a warning.")
        for index, (name, _) in enumerate(entries):
            for other, _ in entries[index + 1 :]:
                lines.append(
                    f'static_assert({name} != {other}, "{name} and {other} must not share a pin");'
                )
        lines.append("")
    elif len(entries) > MAX_STATIC_ASSERT_PINS:
        lines.append(
            f"// {len(entries)} pins claimed; pairwise static asserts omitted above "
            f"{MAX_STATIC_ASSERT_PINS}."
        )
        lines.append("")

    if namespace:
        lines += [f"}}  // namespace {namespace}", ""]

    if guard:
        lines += [f"#endif  // {guard}", ""]

    return "\n".join(lines).rstrip("\n") + "\n"


def to_python_module(registry: PinRegistry, *, prefix: str = "PIN_") -> str:
    """Emit the same constants for the MicroPython half of a project."""
    entries = _unique_identifiers(registry.assignments, prefix)
    profile = registry.profile
    lines = [
        '"""Generated by pinguard. Edit the pin map, not this file."""',
        "",
        f"BOARD = {profile.name!r}",
        f"FINGERPRINT = {profile.fingerprint()!r}",
        "",
    ]
    for name, assignment in entries:
        comment = _comment(registry, assignment)
        suffix = f"  # {comment}" if comment else ""
        lines.append(f"{name} = {assignment.pin}{suffix}")
    lines.append("")
    lines.append("BY_ROLE = {")
    for name, assignment in entries:
        lines.append(f"    {assignment.role!r}: {name},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def to_markdown(registry: PinRegistry) -> str:
    """A table for the README of whatever this board ends up being."""
    profile = registry.profile
    lines = [
        f"# {profile.display_name or profile.name} pin map",
        "",
        "| Pin | Role | Used for | Notes |",
        "| --- | ---- | -------- | ----- |",
    ]
    for assignment in registry.assignments:
        spec = profile.pin(assignment.pin)
        caps = ", ".join(c.value for c in assignment.capabilities) or "-"
        notes = "; ".join(filter(None, [spec.notes, assignment.note])) or ""
        lines.append(f"| GPIO{assignment.pin} | `{assignment.role}` | {caps} | {notes} |")
    if registry.advisories:
        lines += ["", "## Advisories", ""]
        lines += [f"- {item}" for item in registry.advisories]
    return "\n".join(lines) + "\n"


FORMATS = {
    "cpp": to_cpp_header,
    "python": to_python_module,
    "markdown": to_markdown,
}


def render(registry: PinRegistry, fmt: str) -> str:
    try:
        renderer = FORMATS[fmt]
    except KeyError as exc:
        raise ValueError(f"unknown format {fmt!r}; expected {', '.join(sorted(FORMATS))}") from exc
    return renderer(registry)


__all__ = [
    "FORMATS",
    "MAX_STATIC_ASSERT_PINS",
    "identifier",
    "render",
    "to_cpp_header",
    "to_markdown",
    "to_python_module",
]
